version: '3'

services:
    badmovies:
        build: .
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        env_file:
            - .env
        restart: unless-stopped
